#!/bin/bash
# @, aka monkey-tail
# Licenced under the GNU GPLv2

###########################################################################
# Globals

SELF=$( basename $0 )
SELF_LONG=$0
SELF_VERSION="0.01"
SELF_AUTHOR="Lucas Martin-King"

###########################################################################
# Embedded help

# |start|<program>|start a program detached from a terminal|
# |run-once|<program>|only start a program if it isn't running|
# |disk-usage|<path>|show disk usage|
# |disk-hogs|<path>|show top 10 disk hogs|
# |disk-free|<path>|show free space|
# |mem-used||show used memory|
# |mem-free||show free memory|
# |mem-total||show total memory|
# |proc|<name or pid>|show process info|
# |proc-tree|<name or pid>|show process tree|
# |proc-files|<name or pid>|show process files|

###########################################################################
# Subcommands

_start () {
 [ -z "$1" ] && return
 ( nohup $* > /dev/null 2>&1 & ) > /dev/null 2>&1
}

_run-once () {
 pidof $1 || _start $*
}

_disk-usage () {
 local dir="."
 [[ ! -z "$1" ]] && dir=$1
 du -chs $1 | tail -n 1
}

_disk-hogs () {
 IFS="$(printf '\n\t')"
 if [[ ! -z "$1" ]] ; then
  [[ ! -d $1 ]] && exit 1
  [[ -d $1 ]] && cd $1
 fi 
 dirs="$( ls -A . )"
 du -sk $dirs | sort -nr | head -n 10 | cut -f 2 |
 xargs -i% du --max-depth=0 -h "%"
}

_disk-free () {
 local dir="."
 [[ ! -z "$1" ]] && dir=$1
 df -h $dir
}

_mem-free () {
 free -m | head -n 3 | tail -n 1 | awk '{ print $4"M" }'
}

_mem-used () {
 free -m | head -n 3 | tail -n 1 | awk '{ print $3"M" }'
}

_mem-total () {
 free -m | grep "Mem:" | awk '{ print $2"M" }'
}

_proc () {
 ps -H -o uname,tty=TTY,pid,pcpu,pmem,rss,comm -C $1
}

_proc-tree () {
 for pid in $(pidof $1) ; do
  pstree -l $pid
 done
}

_proc-files () {
 local opt="-c $1"
 is_numeric $1 && opt="-p $1"
 lsof -f $opt | grep -v "/lib\|/usr/lib\|/usr/local/lib\| socket\| pipe\| anon_inode"
}

###########################################################################
# Helper commands

_help () {
 echo "Usage: $SELF <subcommand>"
 exit 1
}

_version () {
 echo "$SELF, version $SELF_VERSION, by $SELF_AUTHOR"
 exit 0
}

_list-commands () {
 declare -F | cut -d ' ' -f 3 | grep "^_.*" | sed 's/^_//' | column
}

_help-on () {
 local cmd=$1
 grep "^# |$cmd|" $SELF_LONG | sed -e 's/# |//' -e 's/|$//' -e 's/|/\t/g'
}

###########################################################################
# Helper functions

catch_all () {
 case "$1" in
  '-v' | '-version' | '--version') _version ;;
  '-h' | '-help' | '--help') _help ;;
 esac

 [[ ! -z "$1" ]] && echo "Command '$1' does not exist"

 _help
}

fn_exists () {
 type $1 2> /dev/null | grep -q 'function'
}

is_numeric () {
 echo "$@" | grep -q -v "[^0-9]"
}

die () {
 echo "error: $1" ; exit 1
}

warn () {
 echo "warning: $1"
}

###########################################################################
# Program

fn_exists _$1 || catch_all $1
CMD=$1 ; shift ; _$CMD $*
